apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  template:
    spec:
      containers:
      - name: webapp
        env:
        - name: SPRING_DATASOURCE_HIKARI_MAX-LIFETIME
          value: "30000"
        - name: LOGGING_LEVEL_COM_ZAXXER_HIKARI
          value: "DEBUG"
        - name: APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
          value: "DEBUG"

