name: Create Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            cd aib
            sed -i -e "s/<subscriptionID>/${{ secrets.SUBSCRIPTIONID }}/g" imageTemplateWin.json
            sed -i -e "s/<rgName>/${{ secrets.IMAGERESOURCEGROUP }}/g" imageTemplateWin.json
            sed -i -e "s/<region>/${{ secrets.LOCATION }}/g" imageTemplateWin.json
            sed -i -e "s/<imageName>/${{ secrets.IMAGENAME }}/g" imageTemplateWin.json
            sed -i -e "s/<runOutputName>/${{ secrets.RUNOUTPUTNAME }}/g" imageTemplateWin.json
            sed -i -e "s/<imgBuilderId>/${{ secrets.IMGBUILDERID }}/g" imageTemplateWin.json
            az resource create -g ${{ secrets.IMAGERESOURCEGROUP }} --properties @imageTemplateWin.json --is-full-object --resource-type Microsoft.VirtualMachineImages/imageTemplates -n aksWorkshopImageTemplateWin01 
