name: Day5 Post - Delete All Resources

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.45.0
          inlineScript: |
            mkdir $GITHUB_WORKSPACE/bin
            export PATH=$PATH:$GITHUB_WORKSPACE/bin
            az config set extension.use_dynamic_install=yes_without_prompt
            az aks install-cli --install-location $GITHUB_WORKSPACE/bin/kubectl
            cd $GITHUB_WORKSPACE
            chmod +x $GITHUB_WORKSPACE/utils/recover_from_node_failure.sh
            chmod +x $GITHUB_WORKSPACE/utils/delete_web_app.sh
            chmod +x $GITHUB_WORKSPACE/utils/update_node_count.sh
            chmod +x $GITHUB_WORKSPACE/utils/disable_all_webtests.sh
            chmod +x $GITHUB_WORKSPACE/utils/delete_day5.sh
            $GITHUB_WORKSPACE/utils/delete_day5.sh
