name: Deploy Azure resources

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            cd bicep
            az deployment sub create -l ${{ secrets.LOCATION }} \
              --name aksWorkshopDeployment \
              --template-file=main.bicep \
              --parameters adminPassword=${{ secrets.ADMINPASSWORD }} \
              --parameters imageReferenceId=${{ secrets.IMAGEREFERENCEID }} \
              --parameters sqlAdminPassword=${{ secrets.SQLADMINPASSWORD }} \
              --parameters numOfUsers=${{ secrets.VMCOUNT }}
            
