name: Deploy Day2 ARM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.45.0
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            cd bicep
            Q='Resources
            | where type =~ "Microsoft.Network/publicIPAddresses"
            | where resourceGroup startswith "MC_aksWorkshopRG-"
            | where tags["k8s-azure-service"] =~ "day2/webapp"
            | project id'

            az graph query -q "$Q" --query "data[].id" -o json > serviceIPs.json

            az deployment sub create -l ${{ secrets.LOCATION }} \
                --name aksWorkshopDeploymentDay2 \
                --template-file=../bicep/day2.bicep \
                --parameters serviceIPs=@serviceIPs.json \
                --parameters numOfUsers=${{ secrets.VMCOUNT }}