name: Start All VMs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az vm start --ids $(az graph query -q 'Resources | where type =~ "Microsoft.Compute/VirtualMachines" | where resourceGroup startswith "aksWorkshopRG-"' --query "data[].id" -o tsv)           
