name: Start the image-building process

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.45.0
          inlineScript: |
            az resource invoke-action -g ${{ secrets.IMAGERESOURCEGROUP }} --resource-type Microsoft.VirtualMachineImages/imageTemplates -n aksWorkshopImageTemplateWin01 --action Run
